from metrics import single_class_precision, single_class_recall
from tensorflow.keras.models import load_model
import pickle

CLASS_INDEX = []
f = open("./class_index.txt", 'r')
while True:
    line = f.readline().strip()
    if not line:
        break
    CLASS_INDEX.append(line)
f.close()
with open("class.pkl","wb") as fw:
    pickle.dump(CLASS_INDEX, fw)

METRIC = {
    '미텔 스피츠_prec': single_class_precision,
    '미텔 스피츠_recall': single_class_recall,
    '삽살개_prec': single_class_precision,
    '삽살개_recall': single_class_recall,
    '비숑 프리제_prec': single_class_precision,
    '비숑 프리제_recall': single_class_recall,
    '샤페이_prec': single_class_precision,
    '샤페이_recall': single_class_recall,
    '아메리칸불리_prec': single_class_precision,
    '아메리칸불리_recall': single_class_recall,
    '아메리칸 아키다_prec': single_class_precision,
    '아메리칸 아키다_recall': single_class_recall,
    '잭 러셀 테리어_prec': single_class_precision,
    '잭 러셀 테리어_recall': single_class_recall,
    '진도견_prec': single_class_precision,
    '진도견_recall': single_class_recall,
    '케인 코르소_prec': single_class_precision,
    '케인 코르소_recall': single_class_recall,
    '터키시 앙고라_prec': single_class_precision,
    '터키시 앙고라_recall': single_class_recall,
    '풍산견_prec': single_class_precision,
    '풍산견_recall': single_class_recall,
    '그레이트 피레니즈_prec': single_class_precision,
    '그레이트 피레니즈_recall': single_class_recall,
    '러시안 블루_prec': single_class_precision,
    '러시안 블루_recall': single_class_recall,
    '미니어쳐 핀셔_prec': single_class_precision,
    '미니어쳐 핀셔_recall': single_class_recall,
    '레그돌_prec': single_class_precision,
    '레그돌_recall': single_class_recall,
    '벵갈_prec': single_class_precision,
    '벵갈_recall': single_class_recall,
    '비글_prec': single_class_precision,
    '비글_recall': single_class_recall,
    '불독_prec': single_class_precision,
    '불독_recall': single_class_recall,
    '사모예드_prec': single_class_precision,
    '사모예드_recall': single_class_recall,
    '스핑크스_prec': single_class_precision,
    '스핑크스_recall': single_class_recall,
    '퍼그_prec': single_class_precision,
    '퍼그_recall': single_class_recall,
    '페르시안_prec': single_class_precision,
    '페르시안_recall': single_class_recall,
    '포메라니안_prec': single_class_precision,
    '포메라니안_recall': single_class_recall,
    '핏불테리어_prec': single_class_precision,
    '핏불테리어_recall': single_class_recall,
    '롯트와일러_prec': single_class_precision,
    '롯트와일러_recall': single_class_recall,
    '보더 콜리_prec': single_class_precision,
    '보더 콜리_recall': single_class_recall,
    '말티즈_prec': single_class_precision,
    '말티즈_recall': single_class_recall,
    '라브라도 리트리버_prec': single_class_precision,
    '라브라도 리트리버_recall': single_class_recall,
    '브리타니 스파니엘_prec': single_class_precision,
    '브리타니 스파니엘_recall': single_class_recall,
    '셔틀랜드 쉽독_prec': single_class_precision,
    '셔틀랜드 쉽독_recall': single_class_recall,
    '셰퍼드_prec': single_class_precision,
    '셰퍼드_recall': single_class_recall,
    '스탠다드 푸들_prec': single_class_precision,
    '스탠다드 푸들_recall': single_class_recall,
    '시베리안 허스키_prec': single_class_precision,
    '시베리안 허스키_recall': single_class_recall,
    '시츄_prec': single_class_precision,
    '시츄_recall': single_class_recall,
    '올드 잉글리쉬 쉽독_prec': single_class_precision,
    '올드 잉글리쉬 쉽독_recall': single_class_recall,
    '요크셔 테리어_prec': single_class_precision,
    '요크셔 테리어_recall': single_class_recall,
    '잉글리쉬 세터_prec': single_class_precision,
    '잉글리쉬 세터_recall': single_class_recall,
    '치와와_prec': single_class_precision,
    '치와와_recall': single_class_recall,
    '토이 푸들_prec': single_class_precision,
    '토이 푸들_recall': single_class_recall,
    '페키니즈_prec': single_class_precision,
    '페키니즈_recall': single_class_recall,
    '포인터_prec': single_class_precision,
    '포인터_recall': single_class_recall,
    '푸들_prec': single_class_precision,
    '푸들_recall': single_class_recall,
    '프렌치 불독_prec': single_class_precision,
    '프렌치 불독_recall': single_class_recall,
    '슈나우져_prec': single_class_precision,
    '슈나우져_recall': single_class_recall,
    '폭스테리어_prec': single_class_precision,
    '폭스테리어_recall': single_class_recall,
    '화이트테리어_prec': single_class_precision,
    '화이트테리어_recall': single_class_recall,
    '마리노이즈_prec': single_class_precision,
    '마리노이즈_recall': single_class_recall,
    '스피츠_prec': single_class_precision,
    '스피츠_recall': single_class_recall,
    '웰시 코기_prec': single_class_precision,
    '웰시 코기_recall': single_class_recall,
    '아메리칸 쇼트헤어_prec': single_class_precision,
    '아메리칸 쇼트헤어_recall': single_class_recall,
    '그레이 하운드_prec': single_class_precision,
    '그레이 하운드_recall': single_class_recall,
    '골든 리트리버_prec': single_class_precision,
    '골든 리트리버_recall': single_class_recall,
    '스코티시폴드_prec': single_class_precision,
    '스코티시폴드_recall': single_class_recall,
    '아비시니안_prec': single_class_precision,
    '아비시니안_recall': single_class_recall,
    '샴_prec': single_class_precision,
    '샴_recall': single_class_recall,
    '차우차우_prec': single_class_precision,
    '차우차우_recall': single_class_recall,
    '코카 스파니엘_prec': single_class_precision,
    '코카 스파니엘_recall': single_class_recall,
    '노르웨이 숲_prec': single_class_precision,
    '노르웨이 숲_recall': single_class_recall,
    '도베르만_prec': single_class_precision,
    '도베르만_recall': single_class_recall,
    '닥스훈트_prec': single_class_precision,
    '닥스훈트_recall': single_class_recall,
    '베들링턴 테리어_prec': single_class_precision,
    '베들링턴 테리어_recall': single_class_recall,
    '보스턴 테리어_prec': single_class_precision,
    '보스턴 테리어_recall': single_class_recall,
    '브리티시 쇼트헤어_prec': single_class_precision,
    '브리티시 쇼트헤어_recall': single_class_recall,
}

with open("metric.pkl","wb") as fw:
    pickle.dump(METRIC, fw)

